FROM python:3.10

ENV HOST 0.0.0.0
ENV DASH_DEBUG_MODE True
COPY ./ /app
WORKDIR /app
RUN set -ex && \
    pip install -r requirements.txt
EXPOSE 8080
CMD ["gunicorn", "-b", ":8080", "-w", "2", "app:server"]