# The builder image, used to build the virtual environment
FROM python:3.10 as builder

RUN pip install poetry

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /app

COPY pyproject.toml poetry.lock ./
RUN touch README.md

RUN poetry install --without dev --no-root && rm -rf $POETRY_CACHE_DIR

# The runtime image, used to just run the code provided its virtual environment
FROM python:3.10 as runtime

ENV VIRTUAL_ENV=/app/.venv \
    PATH="/app/.venv/bin:$PATH" \
    HOST=0.0.0.0 \
    DASH_DEBUG_MODE=True
COPY --from=builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}

COPY data/ ./data
COPY app.py ./
COPY pages/ ./pages

EXPOSE 8080
CMD ["gunicorn", "-b", ":8080", "-w", "2", "app:server"]
