name: Test app in container

on:
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-app-engine:
    name: Test app in container
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build docker image
      run: |
        make docker

    - name: Test image
      run: |
        docker run --rm -d --name test_container -p 8080:8080 noplp-stats:dev
        docker run --link test_container:test_container waisbrot/wait
        curl --fail -v -o /dev/null http://localhost:8080/global
