name: Test app

on:
  pull_request:
    branches: ["main"]

jobs:
  deploy-test-container:
    name: Test app in container
    runs-on: ubuntu-latest
    permissions:
      contents: "read"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          make docker

      - name: Test image
        run: |
          docker run --rm -d --name test_container -p 8080:8080 noplp-stats:dev
          docker run --link test_container:test_container waisbrot/wait
          curl --fail -v -o /dev/null http://localhost:8080/global

  dash-testing:
    name: Run end-to-end Dash tests
    runs-on: ubuntu-latest
    permissions:
      contents: "read"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install

      - name: Launch tests
        run: |
          export PATH=$PATH:$CHROMEWEBDRIVER
          poetry run pytest --log-cli-level DEBUG --headless

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: npm ci
      # or one-off:
      - run: npm install execa
      - uses: actions/github-script@v7
        with:
          script: |
            const execa = require('execa')

            const { output_python } = await execa('poetry', ['run', 'noplp/compare_changes.py'])

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output_python
            })
