name: "Test: web app"

on:
  pull_request:
    branches: ["main"]

jobs:
  deploy-test-container:
    name: Test app in container
    runs-on: ubuntu-latest
    permissions:
      contents: "read"

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Build docker image
        run: |
          make docker

      - name: Test image
        run: |
          docker run --rm -d --name test_container -p 8080:8080 noplp-stats:dev
          for i in {1..30}; do
            if curl --fail -s http://localhost:8080/global > /dev/null; then
              echo "App is up!"
              break
            fi
            sleep 1
          done
          if ! curl --fail -v -o /dev/null http://localhost:8080/global; then
            echo "App did not start in time" >&2
            exit 1
          fi

  dash-testing:
    name: Run end-to-end Dash tests
    runs-on: ubuntu-latest
    permissions:
      contents: "read"

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up Python 3.12
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.12"
      - name: Install poetry
        run: |
          pipx install git+https://github.com/python-poetry/poetry.git@811a12dae0fe81f199e3f1b88b8b8be9eed543c2 #v2.4.1
          
      - name: Install dependencies
        run: |
          poetry install

      - name: Launch tests
        run: |
          export PATH=$PATH:$CHROMEWEBDRIVER
          poetry run pytest --log-cli-level DEBUG --headless
