name: Deploy to App Engine

on:
  push:
    branches: [main]
    paths:
      - pages/**
      - data/**
      - .github/workflows/deploy.yaml
      - app.py
      - poetry.lock
      - app.yaml
      - .gcloudignore
  pull_request:
    branches: [main]
    paths:
      - pages/**
      - data/**
      - .github/workflows/deploy.yaml
      - app.py
      - poetry.lock
      - app.yaml
      - .gcloudignore

jobs:
  setup-app-engine:
    name: Prepare for App Engine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up Python 3.14
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"
      - name: Install poetry
        run: |
          pipx install git+https://github.com/python-poetry/poetry.git@811a12dae0fe81f199e3f1b88b8b8be9eed543c2 #v2.4.1
      - name: Install dependencies
        run: |
          poetry self add poetry-plugin-export
          poetry export -f requirements.txt --output requirements.txt --only main
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: requirements
          path: requirements.txt

  deploy-production-app-engine:
    name: Deploy App Engine (production)
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write" # for OpenID Connect JWT Token
    needs: setup-app-engine
    environment:
      name: production
      url: ${{ steps.deploy.outputs.version_url }}
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: GCP authentication
        uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2.1.13
        with:
          workload_identity_provider: ${{ secrets.OIDC_PROVIDER }}
          service_account: ${{ secrets.GCP_SA }}

      - name: Get requirements.txt
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: requirements

      - name: Prepapre app.yaml file for production deployment
        run: 'cp deploy/app-main.yaml app.yaml'

      - name: Deploy App Engine
        uses: google-github-actions/deploy-appengine@a343979004148afb93c94c712b467e8e9f01b06b # v2.1.8
        with:
          flags: "--no-cache"

      - name: "Clean temporary container images"
        run: |-
          gcloud artifacts docker images delete europe-west6-docker.pkg.dev/noplp-stats/gae-standard/app/default

  deploy-pr-app-engine:
    name: Deploy App Engine (pull_request)
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write" # for OpenID Connect JWT Token
    needs: setup-app-engine
    environment:
      name: pull_request
      url: ${{ steps.deploy.outputs.version_url }}
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: GCP authentication
        uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2.1.13
        with:
          workload_identity_provider: ${{ secrets.OIDC_PROVIDER }}
          service_account: ${{ secrets.GCP_SA }}

      - name: Get requirements.txt
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: requirements

      - name: Prepapre app.yaml file for PR deployment
        run: 'cp deploy/app-pr.yaml app.yaml'

      - name: Deploy App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@a343979004148afb93c94c712b467e8e9f01b06b # v2.1.8
        with:
          flags: "--no-cache"
          promote: false

      - name: Show PR environment URL
        run: 'echo "${{ steps.deploy.outputs.version_url }}"'

      - name: Clean temporary container images
        run: |-
          gcloud artifacts docker images delete europe-west6-docker.pkg.dev/noplp-stats/gae-standard/app/default
