name: Deploy to App Engine

on:
  push:
    branches: [ main, 11-add-cd ]
  pull_request:
    branches: [ main, 11-add-cd ]

jobs:
  deploy-app-engine:
    name: Deploy on App Engine
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/473129746304/locations/global/workloadIdentityPools/github-pool/providers/github-action-provider'
        service_account: 'app-engine-github-action@noplp-stats.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v1'
