name: Test scrapping script

on:
  pull_request:
    branches: ["main"]
    paths: ["noplp/**"]

jobs:
  scraping-testing:
    name: Run scrapping test
    runs-on: ubuntu-latest
    permissions:
      contents: "read"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v2.2.0

      - name: Install dependencies
        run: |
          poetry install

      - name: Launch scrapping test
        run: |
          poetry run python noplp/create_database.py --test

      - name: Launch pages tests
        run: |
          poetry run pytest tests/test_all.py
