name: "Test: scrapping script"

on:
  pull_request:
    branches: ["main"]
    paths:
      - "noplp/**"
      - "poetry.lock"

jobs:
  scraping-testing:
    name: Run scrapping test
    runs-on: ubuntu-latest
    permissions:
      contents: "read"

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Python 3.14
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"
      - name: Install poetry
        run: |
          pipx install git+https://github.com/python-poetry/poetry.git@811a12dae0fe81f199e3f1b88b8b8be9eed543c2 #v2.4.1
          
      - name: Install dependencies
        run: |
          poetry install

      - name: Launch scrapping test
        run: |
          poetry run python noplp/create_database.py --test

      - name: Launch pages tests
        run: |
          export PATH=$PATH:$CHROMEWEBDRIVER
          poetry run pytest --log-cli-level INFO --log-file=tests/artifacts/pytest.log --log-file-level=DEBUG

      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-verbose-logs
          path: tests/artifacts/*.log
