name: "Test: scrapping script"

on:
  pull_request:
    branches: ["main"]
    paths:
      - "noplp/**"
      - "poetry.lock"

jobs:
  scraping-testing:
    name: Run scrapping test
    runs-on: ubuntu-latest
    permissions:
      contents: "read"

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up Python 3.14
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"
      - name: Install poetry
        run: |
          pipx install git+https://github.com/python-poetry/poetry.git@811a12dae0fe81f199e3f1b88b8b8be9eed543c2 #v2.4.1
          
      - name: Install dependencies
        run: |
          poetry install

      - name: Launch scrapping test
        run: |
          poetry run python noplp/create_database.py --test

      - name: Launch pages tests
        run: |
          export PATH=$PATH:$CHROMEWEBDRIVER
          poetry run pytest --log-cli-level DEBUG --headless
